import gradio as gr
from rag import get_response


def chat_interface(user_input):
    response = get_response(user_input)
    return response


# Define Gradio Interface
iface = gr.Interface(
    fn=chat_interface,
    inputs=gr.Textbox(
        lines=2, placeholder="Enter your message here...", label="User Message"
    ),
    outputs=gr.Textbox(label="AI Response"),
    title="LangChain & LangGraph Chatbot",
    description="Enter a message to receive a response generated by the local LLaMA model using LangChain and LangGraph.",
    theme="default",
)

if __name__ == "__main__":
    iface.launch()
